swhen:
  branch: main
  event: ['push']

steps:
  - name: build
    image: node:alpine
    commands:
      - npm install && npm audit fix
      - npm run build
    when:
      event: ['push', 'pull_request']

  - name: surge
    image: node:alpine
    secrets: [surge_login, surge_token]
    commands:
      - npm install surge
      - cp dist/index.html dist/200.html
      - npx surge ./dist --domain https://hyperpipe.surge.sh

  - name: docker
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: codeberg.org/hyperpipe/hyperpipe
      registry: codeberg.org
      tag: latest
      username:
        from_secret: cb_user
      password:
        from_secret: cb_token
