pipeline:
  build:
    image: node:alpine
    commands:
      - npm install && npm audit fix
      - npm run build
    when:
      event: ['push', 'pull_request']

  surge:
    image: node:alpine
    commands:
      - npm install surge
      - cp dist/index.html dist/200.html
      - npx surge ./dist --domain https://hyperpipe.surge.sh
    secrets: [surge_login, surge_token]
    when:
      branch: main
      event: ['push']

  docker:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: 'linux/amd64,linux/arm64/v8'
      repo: codeberg.org/hyperpipe/hyperpipe
      registry: codeberg.org
      tags: latest
      username:
        from_secret: cb_user
      password:
        from_secret: cb_token
    when:
      branch: main
      event: ['push']
