pipeline:
  build:
    image: node:alpine
    commands:
      - npm install
      - npm run build
    when:
      path:
        exclude: [ '*.md', '.gitea/*' ]
      event: ['push', 'pull_request']

  docker:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      repo: codeberg.org/hyperpipe/hyperpipe
      registry: codeberg.org
      tags: latest
      username: snematoda
      password:
        from_secret: cb_token
    when:
      branch: main
      path:
        exclude: [ '*.md', '.gitea/*' ]
      event: ['push']

  deploy:
    image: node:alpine
    commands:
      - npm install surge
      - cp dist/index.html dist/200.html
      - npx surge ./dist hyperpipe.surge.sh
    secrets: [surge_login, surge_token]
    when:
      branch: main
      path:
        exclude: [ '*.md', '.gitea/*' ]
      event: ['push']
